---
:concurrency: 3
:logfile: ./log/sidekiq.json.log
:queues:
  - [webhooks, 1]
  - [default, 10]  # remove this ratio when LLM is using a low priority queue and can cope with lots of requests
  - checks_low
:schedule:
  cleanup:
    every: 60m
    class: CleanupWorker
